title: "Instalguru"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://instalguru.fr" # the base hostname & protocol for your site, e.g. http://example.com
lang: "fr"
photo: "/assets/img/default.jpg"
scvarificationnumber: "7XOqXKAknjHenJTFzOqRbt6d_VUbfWI7XnhzyAbJKnY" # numer identyfikacjyny google search console
analyticsvarificationnumber: "G-08GG7RFE50" # numer identyfikacjyny google analyticks
gtagmanagervarificationnumber:
optimizevarificationnumber:
facebookpixelnumber: "438112533832846" 

markdown: kramdown

remote_theme: arturmatlega/ig-theme

toc:
  min_level: 2
  max_level: 3

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-toc
  - jekyll-remote-theme

ampdir: amp

collections:
  posts:    
    permalink: /blog/:title:output_ext